# Generated by Django 5.2.1 on 2025-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Investment Platform', max_length=100)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('email_host', models.CharField(blank=True, max_length=100, null=True)),
                ('email_port', models.IntegerField(default=587)),
                ('email_host_user', models.CharField(blank=True, max_length=100, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=100, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('btc_address', models.CharField(blank=True, max_length=100, null=True)),
                ('eth_address', models.CharField(blank=True, max_length=100, null=True)),
                ('usdt_address', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_referrals', models.BooleanField(default=True)),
                ('referral_bonus_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('kyc_required', models.BooleanField(default=True)),
                ('kyc_documents_required', models.TextField(blank=True, default='ID Card, Proof of Address, Selfie', null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='We are currently performing maintenance. Please check back later.', null=True)),
                ('min_withdrawal', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('withdrawal_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
