# Generated by Django 5.2.1 on 2025-05-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='expected_profit',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.investmentplan'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='return_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
