# Generated by Django 5.2.1 on 2025-05-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptowallet',
            options={'verbose_name': 'Crypto Wallet', 'verbose_name_plural': 'Crypto Wallets'},
        ),
    ]
