# Generated by Django 5.2.1 on 2025-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_cryptowallet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_address',
            field=models.TextField(blank=True, help_text='Physical address of the bank branch', null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='iban',
            field=models.CharField(blank=True, help_text='International Bank Account Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(blank=True, help_text='ABA/Routing number for US banks', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, help_text='Full card number (stored securely)', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, help_text='Card verification value', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
